---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-breach-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-breach-app
  template:
    metadata:
      labels:
        app: email-breach-app
    spec:
      containers:
        - name: backend
          image: akash2061/ebc_back:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
        - name: frontend
          image: akash2061/ebc_front:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: email-breach-service
spec:
  selector:
    app: email-breach-app
  ports:
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
    - name: backend
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
